"""Print the Gate N pinned values as Markdown (source of ``docs/pinned_values.md``).

Usage (from ``backend/``)::

    uv run python -m app.analytics.generator.pin_targets > ../docs/pinned_values.md

Every number is measured from the landing parquet and the Gate E metrics file; nothing is typed in.
The output is deterministic (no wall clock): re-running on the same landing gives identical bytes.
"""

from __future__ import annotations

import argparse
import json
from datetime import timedelta
from pathlib import Path

from app import settings
from app.analytics.generator import validate as V
from app.analytics.generator.fields import FIELD_CONFIGS
from app.analytics.generator.fields.geleki import PREPEND_SEED

MODEL_METRICS = Path(__file__).resolve().parents[1] / "model" / "survival_model_metrics.json"
TRAILING_12M = (settings.AS_OF - timedelta(days=364), settings.AS_OF)


def _pct(x: float) -> str:
    return f"{x * 100:+.1f}%"


def _table(header: list[str], rows: list[list]) -> list[str]:
    out = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return out


def render(landing: Path) -> str:
    L: list[str] = []
    w = L.append
    w("# WellPulse v0.4 — Gate N pinned values")
    w("")
    w("> **Answer first:** the Stage N synthetic data hits every Gate N target. The values below are the")
    w("> exact numbers BDD scenarios assert from Gate N onward (they replace the «target ± tol» placeholders).")
    w("> Generated by `uv run python -m app.analytics.generator.pin_targets` from `backend/app/data/landing`;")
    seeds = ", ".join(f"{f} {c.seed}" for f, c in FIELD_CONFIGS.items())
    w(f"> data window {settings.DATA_START}..{settings.DATA_END}, AS_OF {settings.AS_OF}; seeds: {seeds} "
      f"(Geleki prepend {PREPEND_SEED}).")
    w("")

    # -- counts --------------------------------------------------------------------------------------
    w("## 1. Wells, clusters and rows")
    w("")
    rows = []
    for f in FIELD_CONFIGS:
        wm = V.load(landing, f.lower(), "well_master")
        dp = V.load(landing, f.lower(), "daily_production")[["production_date", "is_prepend"]] \
            if f == "Geleki" else V.load(landing, f.lower(), "daily_production")[["production_date"]]
        wo = V.load(landing, f.lower(), "workover_history")
        rows.append([f, len(wm), wm["cluster_id"].nunique(), f"{len(dp):,}",
                     f"{dp['production_date'].min()}..{dp['production_date'].max()}", f"{len(wo):,}"])
    L += _table(["Field", "Wells", "Clusters (GGS)", "daily_production rows", "Window", "workover_history rows"], rows)
    w("")
    hist = V.load(landing, "geleki", "daily_production")
    n_points = int(hist[(hist.well_id == "GK-129") & (hist.production_date <= settings.AS_OF)].shape[0])
    w(f"- History points per well for the 5-year range (2021-10-01..AS_OF {settings.AS_OF}): **{n_points}** "
      "(`/api/wells/{id}/history?range=5y`).")
    w("")

    # -- gaps ----------------------------------------------------------------------------------------
    w("## 2. Field production gap vs target (F-09)")
    w("")
    w(f"QTD window {V.QTD[0]}..{V.QTD[1]}; trailing-12-month window {TRAILING_12M[0]}..{TRAILING_12M[1]}. "
      "Target = monthly healthy-state potential × 2021-10..2023-09 plan efficiency (decision N-D5).")
    w("")
    rows = []
    for f in FIELD_CONFIGS:
        tgt, tol = V.GAP_TARGET[f]
        g = V.gap(landing, f, V.QTD)
        rows.append([f, _pct(g), _pct(V.gap(landing, f, TRAILING_12M)), f"{tgt * 100:+.0f}% ± {tol * 100:.0f} pp",
                     "PASS" if abs(g - tgt) <= tol else "FAIL"])
    L += _table(["Field", "QTD gap (pinned)", "Trailing-12m gap", "Design target", "Gate"], rows)
    w("")

    # -- fixtures ------------------------------------------------------------------------------------
    w("## 3. Fixture wells")
    w("")
    k = V.lkw047_waits(landing)
    w(f"- **LKW-047** (Lakwa, GGS-I): pump job `{k['workover_id']}` starts {k['job_start']}; in the 180-day window "
      f"before it: WAIT_ON_RIG **{k['wait_on_rig_days']}** days, WAIT_ON_MATERIAL **{k['wait_on_material_days']}** days "
      f"(status history); operations_events agree: {dict(sorted(k['events'].items()))}.")
    r = V.lkm090_residuals(landing)
    offs = ", ".join(f"{wid} {_pct(v)}" for wid, v in r["offsets"].items())
    w(f"- **LKM-090** (Lakhmani): decline over its signature window **{_pct(r['lkm090_decline'])}**; offsets: {offs}; "
      f"max |residual| **{r['max_abs_residual_pp']:.1f} pp** (contract: ≤ 5 pp).")
    w("")

    # -- join / classifier / model ---------------------------------------------------------------------
    w("## 4. Geleki prepend join (2023-10-01)")
    w("")
    j = V.join_continuity(landing)
    w(f"- 7-day field-total oil before vs after the join: **{_pct(j['field_total_ratio'])}**; "
      f"per producing well: **{_pct(j['per_producing_well_ratio'])}** (contract: within ±3%).")
    w("- Geleki v0.3.0 core rows/columns are hash-identical to `tests/baseline/landing_v030` "
      "(`validate --compare-baseline`).")
    w("")
    w("## 5. Intervention classes (non-censored workovers, all fields)")
    w("")
    ic = V.ic_counts(landing)
    L += _table(["IC", "Rows"], [[c, n] for c, n in ic.items()])
    w("")
    w(f"Minimum **{min(ic.values())}** (contract: ≥ {V.IC_MIN_ROWS} per class).")
    w("")
    w("## 6. Survival model (Gate E regression, `train --exclude-prepend`)")
    w("")
    if MODEL_METRICS.exists():
        m = json.loads(MODEL_METRICS.read_text(encoding="utf-8"))
        w(f"- model_version `{m['model_version']}`, training rows `{m['training_rows']}`: holdout C-index "
          f"**{m['holdout_c_index']}**, Trigger B **{m['trigger_b_c_index']}**, episodes {m['n_episodes_total']} "
          f"(right-censored {m['right_censored_fraction']:.1%}).")
    else:
        w("- metrics file missing: run `uv run python -m app.analytics.model.train --exclude-prepend`.")
    w("")

    # -- asset tables --------------------------------------------------------------------------------
    w("## 7. Asset tables")
    w("")
    rows = [[t, len(V.load(landing, "asset", t))] for t in V.ASSET_TABLES]
    L += _table(["Table", "Rows"], rows)
    w("")
    w("## 8. Placeholders that are NOT pinned at Gate N")
    w("")
    w("- BDD-F01-S03 / S06 loss-attribution shares (SUBSURFACE ≥ 80%, controllable ≤ 15% / ≥ 40%) are outputs of")
    w("  the TC-019 attribution tool and are pinned at Gate P, from this same data.")
    w("")
    w("## 9. Decisions behind these values")
    w("")
    w("- **N-D5** Target = healthy-state potential × baseline plan efficiency; the gap is emergent, measured on QTD.")
    w("- **N-D10** Lakwa: rig-wait drift 14→48 d and preventive-maintenance interval drift 230→120 d over the")
    w("  window (third calibration attempt; earlier attempts gave −8.8% .. −15.4%). The QTD gap moves ±3 pp")
    w("  between seeds, so the pinned value is tied to the committed seeds.")
    w("- **N-D12** The Geleki prepend ends with a WAITING_ON_RIG tail for wells whose frozen core starts down,")
    w("  which brings the field-total join to the value in §4.")
    w("- **N-D9** Health buckets shown in the UI are the interim rule INTERIM_N1 until TC-020 (Stage P).")
    w("")
    return "\n".join(L) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--landing", type=Path, default=settings.LANDING_DIR)
    a = ap.parse_args(argv)
    print(render(a.landing), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
