-- GENERATED by lakehouse/ddl/generate_ddl.py from the landing parquet schemas. Do not edit by hand.

CREATE EXTERNAL TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_bronze.barrier_tests` (
  `well_id` STRING,
  `field` STRING,
  `cluster_id` STRING,
  `test_id` STRING,
  `test_date` DATE,
  `barrier` STRING,
  `result` STRING,
  `test_pressure_kgcm2` FLOAT64,
  `next_due` DATE,
  `is_synthetic` BOOL,
  `_ingested_at` TIMESTAMP,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64
)
WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://workover-operations-agentic-ai-datalake/bronze/barrier_tests/*'],
  hive_partition_uri_prefix = 'gs://workover-operations-agentic-ai-datalake/bronze/barrier_tests',
  require_hive_partition_filter = false,
  description = 'BRONZE barrier_tests: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'
);

CREATE EXTERNAL TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_bronze.casing_tally` (
  `well_id` STRING,
  `field` STRING,
  `cluster_id` STRING,
  `string_type` STRING,
  `od_in` FLOAT64,
  `weight_ppf` FLOAT64,
  `grade` STRING,
  `top_m` FLOAT64,
  `shoe_m` FLOAT64,
  `cement_top_m` FLOAT64,
  `install_date` DATE,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64
)
WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://workover-operations-agentic-ai-datalake/bronze/casing_tally/*'],
  hive_partition_uri_prefix = 'gs://workover-operations-agentic-ai-datalake/bronze/casing_tally',
  require_hive_partition_filter = false,
  description = 'BRONZE casing_tally: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'
);

CREATE EXTERNAL TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_bronze.daily_production` (
  `well_id` STRING,
  `production_date` DATE,
  `oil_rate_bopd` FLOAT64,
  `water_rate_bwpd` FLOAT64,
  `gas_rate_mscfd` FLOAT64,
  `liquid_rate_blpd` FLOAT64,
  `water_cut_pct` FLOAT64,
  `gor_scf_bbl` FLOAT64,
  `thp_kgcm2` FLOAT64,
  `chp_kgcm2` FLOAT64,
  `choke_size_64th` INT64,
  `spm` FLOAT64,
  `runtime_hours` FLOAT64,
  `runtime_fraction` FLOAT64,
  `is_producing` BOOL,
  `downtime_reason` STRING,
  `data_source` STRING,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `field` STRING,
  `cluster_id` STRING,
  `is_prepend` BOOL,
  `wht_degc` FLOAT64,
  `gl_inj_rate_mscfd` FLOAT64,
  `gl_inj_pressure_kgcm2` FLOAT64,
  `_source_row` INT64
)
WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://workover-operations-agentic-ai-datalake/bronze/daily_production/*'],
  hive_partition_uri_prefix = 'gs://workover-operations-agentic-ai-datalake/bronze/daily_production',
  require_hive_partition_filter = false,
  description = 'BRONZE daily_production: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'
);

CREATE EXTERNAL TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_bronze.decision_log` (
  `decision_id` STRING,
  `draft_plan_id` STRING,
  `well_id` STRING,
  `run_date` DATE,
  `decided_at` STRING,
  `decided_by` STRING,
  `decision` STRING,
  `reason_text` STRING,
  `reason_category` STRING,
  `modified_job_code` STRING,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64
)
WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://workover-operations-agentic-ai-datalake/bronze/decision_log/*'],
  hive_partition_uri_prefix = 'gs://workover-operations-agentic-ai-datalake/bronze/decision_log',
  require_hive_partition_filter = false,
  description = 'BRONZE decision_log: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'
);

CREATE EXTERNAL TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_bronze.deviation_survey` (
  `well_id` STRING,
  `field` STRING,
  `cluster_id` STRING,
  `md_m` FLOAT64,
  `inc_deg` FLOAT64,
  `azi_deg` FLOAT64,
  `tvd_m` FLOAT64,
  `dls_deg_30m` FLOAT64,
  `is_synthetic` BOOL,
  `_ingested_at` TIMESTAMP,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64
)
WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://workover-operations-agentic-ai-datalake/bronze/deviation_survey/*'],
  hive_partition_uri_prefix = 'gs://workover-operations-agentic-ai-datalake/bronze/deviation_survey',
  require_hive_partition_filter = false,
  description = 'BRONZE deviation_survey: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'
);

CREATE EXTERNAL TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_bronze.document_index` (
  `doc_id` STRING,
  `well_id` STRING,
  `doc_type` STRING,
  `doc_date` DATE,
  `gcs_uri` STRING,
  `title` STRING,
  `has_text_layer` BOOL,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64
)
WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://workover-operations-agentic-ai-datalake/bronze/document_index/*'],
  hive_partition_uri_prefix = 'gs://workover-operations-agentic-ai-datalake/bronze/document_index',
  require_hive_partition_filter = false,
  description = 'BRONZE document_index: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'
);

CREATE EXTERNAL TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_bronze.draft_plan` (
  `draft_plan_id` STRING,
  `run_date` DATE,
  `well_id` STRING,
  `recommended_job_code` STRING,
  `queue` STRING,
  `requires_rig` BOOL,
  `approval_status` STRING,
  `why_this_well_now` STRING,
  `selection_evidence` STRING,
  `rejected_alternative_code` STRING,
  `rejected_alternative_reason` STRING,
  `deferred_bbl_avoided_12mo` FLOAT64,
  `logistics_blocker` STRING,
  `earliest_start_date` DATE,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64
)
WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://workover-operations-agentic-ai-datalake/bronze/draft_plan/*'],
  hive_partition_uri_prefix = 'gs://workover-operations-agentic-ai-datalake/bronze/draft_plan',
  require_hive_partition_filter = false,
  description = 'BRONZE draft_plan: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'
);

CREATE EXTERNAL TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_bronze.fishing_records` (
  `well_id` STRING,
  `field` STRING,
  `cluster_id` STRING,
  `event_id` STRING,
  `event_date` DATE,
  `fish_type` STRING,
  `top_md_m` FLOAT64,
  `recovered` BOOL,
  `workover_id` STRING,
  `is_synthetic` BOOL,
  `_ingested_at` TIMESTAMP,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64
)
WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://workover-operations-agentic-ai-datalake/bronze/fishing_records/*'],
  hive_partition_uri_prefix = 'gs://workover-operations-agentic-ai-datalake/bronze/fishing_records',
  require_hive_partition_filter = false,
  description = 'BRONZE fishing_records: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'
);

CREATE EXTERNAL TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_bronze.fluid_hazards` (
  `well_id` STRING,
  `field` STRING,
  `cluster_id` STRING,
  `h2s_ppm` FLOAT64,
  `co2_mol_pct` FLOAT64,
  `wax_flag` BOOL,
  `sand_flag` BOOL,
  `scale_flag` BOOL,
  `hazard_class` STRING,
  `is_synthetic` BOOL,
  `_ingested_at` TIMESTAMP,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64
)
WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://workover-operations-agentic-ai-datalake/bronze/fluid_hazards/*'],
  hive_partition_uri_prefix = 'gs://workover-operations-agentic-ai-datalake/bronze/fluid_hazards',
  require_hive_partition_filter = false,
  description = 'BRONZE fluid_hazards: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'
);

CREATE EXTERNAL TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_bronze.formation_tops` (
  `well_id` STRING,
  `field` STRING,
  `cluster_id` STRING,
  `formation` STRING,
  `top_md_m` FLOAT64,
  `bottom_md_m` FLOAT64,
  `lithology` STRING,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64
)
WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://workover-operations-agentic-ai-datalake/bronze/formation_tops/*'],
  hive_partition_uri_prefix = 'gs://workover-operations-agentic-ai-datalake/bronze/formation_tops',
  require_hive_partition_filter = false,
  description = 'BRONZE formation_tops: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'
);

CREATE EXTERNAL TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_bronze.operations_events` (
  `event_id` STRING,
  `well_id` STRING,
  `field` STRING,
  `cluster_id` STRING,
  `start_date` DATE,
  `end_date` DATE,
  `event_type` STRING,
  `factor_class` STRING,
  `controllable` BOOL,
  `responsible_function` STRING,
  `trigger_ref` STRING,
  `is_prepend` BOOL,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64
)
WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://workover-operations-agentic-ai-datalake/bronze/operations_events/*'],
  hive_partition_uri_prefix = 'gs://workover-operations-agentic-ai-datalake/bronze/operations_events',
  require_hive_partition_filter = false,
  description = 'BRONZE operations_events: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'
);

CREATE EXTERNAL TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_bronze.perforation_intervals` (
  `well_id` STRING,
  `field` STRING,
  `cluster_id` STRING,
  `zone` STRING,
  `top_m` FLOAT64,
  `bottom_m` FLOAT64,
  `spf` INT64,
  `perf_date` DATE,
  `status` STRING,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64
)
WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://workover-operations-agentic-ai-datalake/bronze/perforation_intervals/*'],
  hive_partition_uri_prefix = 'gs://workover-operations-agentic-ai-datalake/bronze/perforation_intervals',
  require_hive_partition_filter = false,
  description = 'BRONZE perforation_intervals: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'
);

CREATE EXTERNAL TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_bronze.pressure_surveys` (
  `well_id` STRING,
  `field` STRING,
  `cluster_id` STRING,
  `survey_id` STRING,
  `survey_date` DATE,
  `sbhp_kgcm2` FLOAT64,
  `fbhp_kgcm2` FLOAT64,
  `pi_bpd_per_kgcm2` FLOAT64,
  `fluid_level_m` FLOAT64,
  `datum_tvd_m` FLOAT64,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64
)
WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://workover-operations-agentic-ai-datalake/bronze/pressure_surveys/*'],
  hive_partition_uri_prefix = 'gs://workover-operations-agentic-ai-datalake/bronze/pressure_surveys',
  require_hive_partition_filter = false,
  description = 'BRONZE pressure_surveys: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'
);

CREATE EXTERNAL TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_bronze.tubing_string` (
  `well_id` STRING,
  `field` STRING,
  `cluster_id` STRING,
  `seq` INT64,
  `component` STRING,
  `od_in` FLOAT64,
  `length_m` FLOAT64,
  `top_m` FLOAT64,
  `install_date` DATE,
  `workover_id` STRING,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64
)
WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://workover-operations-agentic-ai-datalake/bronze/tubing_string/*'],
  hive_partition_uri_prefix = 'gs://workover-operations-agentic-ai-datalake/bronze/tubing_string',
  require_hive_partition_filter = false,
  description = 'BRONZE tubing_string: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'
);

CREATE EXTERNAL TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_bronze.tubing_tally` (
  `well_id` STRING,
  `field` STRING,
  `cluster_id` STRING,
  `joint_no` INT64,
  `component_type` STRING,
  `top_md_m` FLOAT64,
  `bottom_md_m` FLOAT64,
  `length_m` FLOAT64,
  `od_in` FLOAT64,
  `id_in` FLOAT64,
  `drift_in` FLOAT64,
  `grade` STRING,
  `weight_ppf` FLOAT64,
  `is_synthetic` BOOL,
  `_ingested_at` TIMESTAMP,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64
)
WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://workover-operations-agentic-ai-datalake/bronze/tubing_tally/*'],
  hive_partition_uri_prefix = 'gs://workover-operations-agentic-ai-datalake/bronze/tubing_tally',
  require_hive_partition_filter = false,
  description = 'BRONZE tubing_tally: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'
);

CREATE EXTERNAL TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_bronze.well_master` (
  `well_id` STRING,
  `field` STRING,
  `asset` STRING,
  `latitude` FLOAT64,
  `longitude` FLOAT64,
  `spud_date` DATE,
  `completion_date` DATE,
  `current_zone` STRING,
  `perf_top_m` FLOAT64,
  `perf_bottom_m` FLOAT64,
  `total_depth_md_m` FLOAT64,
  `total_depth_tvd_m` FLOAT64,
  `max_dls_deg_30m` FLOAT64,
  `lift_type` STRING,
  `plunger_diameter_in` FLOAT64,
  `stroke_length_in` FLOAT64,
  `pump_setting_depth_m` FLOAT64,
  `rod_string_grade` STRING,
  `pump_type` STRING,
  `casing_vented` BOOL,
  `tubing_size_in` FLOAT64,
  `casing_size_in` FLOAT64,
  `status` STRING,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `cluster_id` STRING,
  `_source_row` INT64
)
WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://workover-operations-agentic-ai-datalake/bronze/well_master/*'],
  hive_partition_uri_prefix = 'gs://workover-operations-agentic-ai-datalake/bronze/well_master',
  require_hive_partition_filter = false,
  description = 'BRONZE well_master: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'
);

CREATE EXTERNAL TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_bronze.well_offsets` (
  `well_id` STRING,
  `offset_well_id` STRING,
  `distance_m` FLOAT64,
  `same_zone` BOOL,
  `rank` INT64,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64
)
WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://workover-operations-agentic-ai-datalake/bronze/well_offsets/*'],
  hive_partition_uri_prefix = 'gs://workover-operations-agentic-ai-datalake/bronze/well_offsets',
  require_hive_partition_filter = false,
  description = 'BRONZE well_offsets: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'
);

CREATE EXTERNAL TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_bronze.well_run` (
  `run_date` DATE,
  `well_id` STRING,
  `trigger_a` STRING,
  `trigger_a_days` INT64,
  `trigger_a_residual_pct` FLOAT64,
  `trigger_b` BOOL,
  `trigger_b_days_since` FLOAT64,
  `trigger_b_p50_days` FLOAT64,
  `trigger_c` STRING,
  `trigger_d` BOOL,
  `mechanism` STRING,
  `mechanism_confidence` STRING,
  `chan_class` STRING,
  `chan_wor_slope` FLOAT64,
  `fillage_gap_blpd` FLOAT64,
  `offset_verdict` STRING,
  `rejected_mechanisms` STRING,
  `ettf_days` FLOAT64,
  `ettf_ci_low` FLOAT64,
  `ettf_ci_high` FLOAT64,
  `hazard` FLOAT64,
  `recommended_job_code` STRING,
  `requires_rig` BOOL,
  `est_duration_days` FLOAT64,
  `p_success` FLOAT64,
  `p_success_n` INT64,
  `deferred_bbl_avoided` FLOAT64,
  `net_value` FLOAT64,
  `priority` FLOAT64,
  `rank_overall` FLOAT64,
  `rank_within_queue` FLOAT64,
  `queue` STRING,
  `logistics_blocker` STRING,
  `earliest_start_date` DATE,
  `tool_trace` STRING,
  `model_version` STRING,
  `config_version` STRING,
  `data_as_of` DATE,
  `data_lag_days` INT64,
  `run_confidence` STRING,
  `confidence_reason` STRING,
  `tested_days_90d` INT64,
  `allocation_basis_id` STRING,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64
)
WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://workover-operations-agentic-ai-datalake/bronze/well_run/*'],
  hive_partition_uri_prefix = 'gs://workover-operations-agentic-ai-datalake/bronze/well_run',
  require_hive_partition_filter = false,
  description = 'BRONZE well_run: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'
);

CREATE EXTERNAL TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_bronze.well_status_history` (
  `episode_id` STRING,
  `well_id` STRING,
  `status` STRING,
  `start_date` DATE,
  `end_date` DATE,
  `reason_code` STRING,
  `is_rigless` BOOL,
  `workover_id` STRING,
  `deferred_bbl` FLOAT64,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `field` STRING,
  `cluster_id` STRING,
  `is_prepend` BOOL,
  `_source_row` INT64
)
WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://workover-operations-agentic-ai-datalake/bronze/well_status_history/*'],
  hive_partition_uri_prefix = 'gs://workover-operations-agentic-ai-datalake/bronze/well_status_history',
  require_hive_partition_filter = false,
  description = 'BRONZE well_status_history: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'
);

CREATE EXTERNAL TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_bronze.well_tests` (
  `test_id` STRING,
  `well_id` STRING,
  `test_date` DATE,
  `test_duration_hr` FLOAT64,
  `oil_rate_bopd` FLOAT64,
  `water_rate_bwpd` FLOAT64,
  `gas_rate_mscfd` FLOAT64,
  `thp_kgcm2` FLOAT64,
  `chp_kgcm2` FLOAT64,
  `fluid_level_m` FLOAT64,
  `pump_intake_p_kgcm2` FLOAT64,
  `test_quality` STRING,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `field` STRING,
  `cluster_id` STRING,
  `is_prepend` BOOL,
  `_source_row` INT64
)
WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://workover-operations-agentic-ai-datalake/bronze/well_tests/*'],
  hive_partition_uri_prefix = 'gs://workover-operations-agentic-ai-datalake/bronze/well_tests',
  require_hive_partition_filter = false,
  description = 'BRONZE well_tests: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'
);

CREATE EXTERNAL TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_bronze.wellhead_rating` (
  `well_id` STRING,
  `field` STRING,
  `cluster_id` STRING,
  `wellhead_class_psi` INT64,
  `xmas_tree_rating_psi` INT64,
  `last_service_date` DATE,
  `is_synthetic` BOOL,
  `_ingested_at` TIMESTAMP,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64
)
WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://workover-operations-agentic-ai-datalake/bronze/wellhead_rating/*'],
  hive_partition_uri_prefix = 'gs://workover-operations-agentic-ai-datalake/bronze/wellhead_rating',
  require_hive_partition_filter = false,
  description = 'BRONZE wellhead_rating: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'
);

CREATE EXTERNAL TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_bronze.workover_history` (
  `workover_id` STRING,
  `well_id` STRING,
  `start_date` DATE,
  `end_date` DATE,
  `job_code` STRING,
  `failure_code` STRING,
  `is_rigless` BOOL,
  `rig_id` STRING,
  `rig_days` FLOAT64,
  `pre_job_oil_bopd` FLOAT64,
  `post_job_oil_bopd` FLOAT64,
  `uplift_bopd` FLOAT64,
  `outcome` STRING,
  `run_life_days` INT64,
  `is_censored` BOOL,
  `damage_reset_frac` FLOAT64,
  `report_doc_id` STRING,
  `catalogue_job_code` STRING,
  `intervention_class` STRING,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `field` STRING,
  `cluster_id` STRING,
  `is_prepend` BOOL,
  `_source_row` INT64
)
WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://workover-operations-agentic-ai-datalake/bronze/workover_history/*'],
  hive_partition_uri_prefix = 'gs://workover-operations-agentic-ai-datalake/bronze/workover_history',
  require_hive_partition_filter = false,
  description = 'BRONZE workover_history: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'
);

CREATE EXTERNAL TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_bronze.cluster_master` (
  `cluster_id` STRING,
  `field` STRING,
  `cluster_type` STRING,
  `polygon_ref` STRING,
  `center_lat` FLOAT64,
  `center_lon` FLOAT64,
  `n_wells` INT64,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64
)
WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://workover-operations-agentic-ai-datalake/bronze/cluster_master/*'],
  hive_partition_uri_prefix = 'gs://workover-operations-agentic-ai-datalake/bronze/cluster_master',
  require_hive_partition_filter = false,
  description = 'BRONZE cluster_master: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'
);

CREATE EXTERNAL TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_bronze.facility_master` (
  `facility_id` STRING,
  `field` STRING,
  `type` STRING,
  `name` STRING,
  `lat` FLOAT64,
  `lon` FLOAT64,
  `capacity_bopd` INT64,
  `serviced_cluster_ids` STRING,
  `compressor_capacity_mmscfd` FLOAT64,
  `water_handling_bwpd` FLOAT64,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64
)
WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://workover-operations-agentic-ai-datalake/bronze/facility_master/*'],
  hive_partition_uri_prefix = 'gs://workover-operations-agentic-ai-datalake/bronze/facility_master',
  require_hive_partition_filter = false,
  description = 'BRONZE facility_master: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'
);

CREATE EXTERNAL TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_bronze.field_master` (
  `field` STRING,
  `asset` STRING,
  `prefix` STRING,
  `centroid_lat` FLOAT64,
  `centroid_lon` FLOAT64,
  `n_wells` INT64,
  `primary_reservoirs` STRING,
  `boundary_geojson` STRING,
  `is_synthetic_geometry` BOOL,
  `data_start` DATE,
  `data_end` DATE,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64
)
WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://workover-operations-agentic-ai-datalake/bronze/field_master/*'],
  hive_partition_uri_prefix = 'gs://workover-operations-agentic-ai-datalake/bronze/field_master',
  require_hive_partition_filter = false,
  description = 'BRONZE field_master: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'
);

CREATE EXTERNAL TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_bronze.field_targets` (
  `field` STRING,
  `month` DATE,
  `target_oil_bopd` FLOAT64,
  `target_uptime_pct` FLOAT64,
  `potential_oil_bopd` FLOAT64,
  `plan_efficiency` FLOAT64,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64
)
WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://workover-operations-agentic-ai-datalake/bronze/field_targets/*'],
  hive_partition_uri_prefix = 'gs://workover-operations-agentic-ai-datalake/bronze/field_targets',
  require_hive_partition_filter = false,
  description = 'BRONZE field_targets: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'
);

CREATE EXTERNAL TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_bronze.job_catalogue` (
  `job_code` STRING,
  `job_name` STRING,
  `category` STRING,
  `mechanism_code` STRING,
  `selection_evidence` STRING,
  `requires_rig` BOOL,
  `equipment` STRING,
  `est_days` FLOAT64,
  `est_cost_lakh_inr` FLOAT64,
  `cost_band` STRING,
  `intervention_class` STRING,
  `sop_doc_id` STRING,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64
)
WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://workover-operations-agentic-ai-datalake/bronze/job_catalogue/*'],
  hive_partition_uri_prefix = 'gs://workover-operations-agentic-ai-datalake/bronze/job_catalogue',
  require_hive_partition_filter = false,
  description = 'BRONZE job_catalogue: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'
);

CREATE EXTERNAL TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_bronze.mro_inventory` (
  `item_code` STRING,
  `item_name` STRING,
  `base` STRING,
  `qty_on_hand` INT64,
  `transit_days` INT64,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64
)
WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://workover-operations-agentic-ai-datalake/bronze/mro_inventory/*'],
  hive_partition_uri_prefix = 'gs://workover-operations-agentic-ai-datalake/bronze/mro_inventory',
  require_hive_partition_filter = false,
  description = 'BRONZE mro_inventory: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'
);

CREATE EXTERNAL TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_bronze.rig_calendar` (
  `rig_id` STRING,
  `date` DATE,
  `status` STRING,
  `well_id` STRING,
  `rig_class` STRING,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64
)
WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)
OPTIONS (
  format = 'PARQUET',
  uris = ['gs://workover-operations-agentic-ai-datalake/bronze/rig_calendar/*'],
  hive_partition_uri_prefix = 'gs://workover-operations-agentic-ai-datalake/bronze/rig_calendar',
  require_hive_partition_filter = false,
  description = 'BRONZE rig_calendar: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'
);
