-- GENERATED by lakehouse/ddl/generate_ddl.py from the landing parquet schemas. Do not edit by hand.

CREATE TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_silver.casing_tally` (
  `well_id` STRING NOT NULL,
  `field` STRING,
  `cluster_id` STRING,
  `string_type` STRING NOT NULL,
  `od_in` FLOAT64,
  `weight_ppf` FLOAT64,
  `grade` STRING,
  `top_m` FLOAT64,
  `shoe_m` FLOAT64,
  `cement_top_m` FLOAT64,
  `install_date` DATE,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64 OPTIONS(description='0-based row ordinal in the landing file (preserves file order)'),
  `_landing_folder` STRING OPTIONS(description='Landing folder: asset | geleki | lakwa | lakhmani'),
  `_bronze_dt` DATE OPTIONS(description='Bronze batch partition (dt=)'),
  `_silver_loaded_at` TIMESTAMP OPTIONS(description='Silver load time')
)
CLUSTER BY well_id
OPTIONS (
  description = 'SILVER casing_tally: typed, de-duplicated on (well_id, string_type); loaded by lakehouse/load/bronze_to_silver.py.',
  labels = [('app', 'wellpulse'), ('stage', 'x'), ('datacloud', 'jetski')]
);

CREATE TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_silver.daily_production` (
  `well_id` STRING NOT NULL,
  `production_date` DATE NOT NULL,
  `oil_rate_bopd` FLOAT64,
  `water_rate_bwpd` FLOAT64,
  `gas_rate_mscfd` FLOAT64,
  `liquid_rate_blpd` FLOAT64,
  `water_cut_pct` FLOAT64,
  `gor_scf_bbl` FLOAT64,
  `thp_kgcm2` FLOAT64,
  `chp_kgcm2` FLOAT64,
  `choke_size_64th` INT64,
  `spm` FLOAT64,
  `runtime_hours` FLOAT64,
  `runtime_fraction` FLOAT64,
  `is_producing` BOOL,
  `downtime_reason` STRING,
  `data_source` STRING,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `field` STRING,
  `cluster_id` STRING,
  `is_prepend` BOOL,
  `wht_degc` FLOAT64,
  `gl_inj_rate_mscfd` FLOAT64,
  `gl_inj_pressure_kgcm2` FLOAT64,
  `_source_row` INT64 OPTIONS(description='0-based row ordinal in the landing file (preserves file order)'),
  `_landing_folder` STRING OPTIONS(description='Landing folder: asset | geleki | lakwa | lakhmani'),
  `_bronze_dt` DATE OPTIONS(description='Bronze batch partition (dt=)'),
  `_silver_loaded_at` TIMESTAMP OPTIONS(description='Silver load time')
)
PARTITION BY production_date
CLUSTER BY field, well_id
OPTIONS (
  description = 'SILVER daily_production: typed, de-duplicated on (well_id, production_date); loaded by lakehouse/load/bronze_to_silver.py.',
  labels = [('app', 'wellpulse'), ('stage', 'x'), ('datacloud', 'jetski')]
);

CREATE TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_silver.decision_log` (
  `decision_id` STRING NOT NULL,
  `draft_plan_id` STRING,
  `well_id` STRING,
  `run_date` DATE,
  `decided_at` STRING,
  `decided_by` STRING,
  `decision` STRING,
  `reason_text` STRING,
  `reason_category` STRING,
  `modified_job_code` STRING,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64 OPTIONS(description='0-based row ordinal in the landing file (preserves file order)'),
  `_landing_folder` STRING OPTIONS(description='Landing folder: asset | geleki | lakwa | lakhmani'),
  `_bronze_dt` DATE OPTIONS(description='Bronze batch partition (dt=)'),
  `_silver_loaded_at` TIMESTAMP OPTIONS(description='Silver load time')
)
CLUSTER BY well_id
OPTIONS (
  description = 'SILVER decision_log: typed, de-duplicated on (decision_id); loaded by lakehouse/load/bronze_to_silver.py.',
  labels = [('app', 'wellpulse'), ('stage', 'x'), ('datacloud', 'jetski')]
);

CREATE TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_silver.document_index` (
  `doc_id` STRING NOT NULL,
  `well_id` STRING,
  `doc_type` STRING,
  `doc_date` DATE,
  `gcs_uri` STRING,
  `title` STRING,
  `has_text_layer` BOOL,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64 OPTIONS(description='0-based row ordinal in the landing file (preserves file order)'),
  `_landing_folder` STRING OPTIONS(description='Landing folder: asset | geleki | lakwa | lakhmani'),
  `_bronze_dt` DATE OPTIONS(description='Bronze batch partition (dt=)'),
  `_silver_loaded_at` TIMESTAMP OPTIONS(description='Silver load time')
)
CLUSTER BY well_id
OPTIONS (
  description = 'SILVER document_index: typed, de-duplicated on (doc_id); loaded by lakehouse/load/bronze_to_silver.py.',
  labels = [('app', 'wellpulse'), ('stage', 'x'), ('datacloud', 'jetski')]
);

CREATE TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_silver.draft_plan` (
  `draft_plan_id` STRING NOT NULL,
  `run_date` DATE,
  `well_id` STRING,
  `recommended_job_code` STRING,
  `queue` STRING,
  `requires_rig` BOOL,
  `approval_status` STRING,
  `why_this_well_now` STRING,
  `selection_evidence` STRING,
  `rejected_alternative_code` STRING,
  `rejected_alternative_reason` STRING,
  `deferred_bbl_avoided_12mo` FLOAT64,
  `logistics_blocker` STRING,
  `earliest_start_date` DATE,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64 OPTIONS(description='0-based row ordinal in the landing file (preserves file order)'),
  `_landing_folder` STRING OPTIONS(description='Landing folder: asset | geleki | lakwa | lakhmani'),
  `_bronze_dt` DATE OPTIONS(description='Bronze batch partition (dt=)'),
  `_silver_loaded_at` TIMESTAMP OPTIONS(description='Silver load time')
)
CLUSTER BY well_id
OPTIONS (
  description = 'SILVER draft_plan: typed, de-duplicated on (draft_plan_id); loaded by lakehouse/load/bronze_to_silver.py.',
  labels = [('app', 'wellpulse'), ('stage', 'x'), ('datacloud', 'jetski')]
);

CREATE TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_silver.formation_tops` (
  `well_id` STRING NOT NULL,
  `field` STRING,
  `cluster_id` STRING,
  `formation` STRING NOT NULL,
  `top_md_m` FLOAT64,
  `bottom_md_m` FLOAT64,
  `lithology` STRING,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64 OPTIONS(description='0-based row ordinal in the landing file (preserves file order)'),
  `_landing_folder` STRING OPTIONS(description='Landing folder: asset | geleki | lakwa | lakhmani'),
  `_bronze_dt` DATE OPTIONS(description='Bronze batch partition (dt=)'),
  `_silver_loaded_at` TIMESTAMP OPTIONS(description='Silver load time')
)
CLUSTER BY well_id
OPTIONS (
  description = 'SILVER formation_tops: typed, de-duplicated on (well_id, formation); loaded by lakehouse/load/bronze_to_silver.py.',
  labels = [('app', 'wellpulse'), ('stage', 'x'), ('datacloud', 'jetski')]
);

CREATE TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_silver.operations_events` (
  `event_id` STRING NOT NULL,
  `well_id` STRING,
  `field` STRING,
  `cluster_id` STRING,
  `start_date` DATE,
  `end_date` DATE,
  `event_type` STRING,
  `factor_class` STRING,
  `controllable` BOOL,
  `responsible_function` STRING,
  `trigger_ref` STRING,
  `is_prepend` BOOL,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64 OPTIONS(description='0-based row ordinal in the landing file (preserves file order)'),
  `_landing_folder` STRING OPTIONS(description='Landing folder: asset | geleki | lakwa | lakhmani'),
  `_bronze_dt` DATE OPTIONS(description='Bronze batch partition (dt=)'),
  `_silver_loaded_at` TIMESTAMP OPTIONS(description='Silver load time')
)
CLUSTER BY well_id
OPTIONS (
  description = 'SILVER operations_events: typed, de-duplicated on (event_id); loaded by lakehouse/load/bronze_to_silver.py.',
  labels = [('app', 'wellpulse'), ('stage', 'x'), ('datacloud', 'jetski')]
);

CREATE TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_silver.perforation_intervals` (
  `well_id` STRING NOT NULL,
  `field` STRING,
  `cluster_id` STRING,
  `zone` STRING NOT NULL,
  `top_m` FLOAT64 NOT NULL,
  `bottom_m` FLOAT64,
  `spf` INT64,
  `perf_date` DATE NOT NULL,
  `status` STRING,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64 OPTIONS(description='0-based row ordinal in the landing file (preserves file order)'),
  `_landing_folder` STRING OPTIONS(description='Landing folder: asset | geleki | lakwa | lakhmani'),
  `_bronze_dt` DATE OPTIONS(description='Bronze batch partition (dt=)'),
  `_silver_loaded_at` TIMESTAMP OPTIONS(description='Silver load time')
)
CLUSTER BY well_id
OPTIONS (
  description = 'SILVER perforation_intervals: typed, de-duplicated on (well_id, zone, top_m, perf_date); loaded by lakehouse/load/bronze_to_silver.py.',
  labels = [('app', 'wellpulse'), ('stage', 'x'), ('datacloud', 'jetski')]
);

CREATE TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_silver.pressure_surveys` (
  `well_id` STRING,
  `field` STRING,
  `cluster_id` STRING,
  `survey_id` STRING NOT NULL,
  `survey_date` DATE,
  `sbhp_kgcm2` FLOAT64,
  `fbhp_kgcm2` FLOAT64,
  `pi_bpd_per_kgcm2` FLOAT64,
  `fluid_level_m` FLOAT64,
  `datum_tvd_m` FLOAT64,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64 OPTIONS(description='0-based row ordinal in the landing file (preserves file order)'),
  `_landing_folder` STRING OPTIONS(description='Landing folder: asset | geleki | lakwa | lakhmani'),
  `_bronze_dt` DATE OPTIONS(description='Bronze batch partition (dt=)'),
  `_silver_loaded_at` TIMESTAMP OPTIONS(description='Silver load time')
)
CLUSTER BY well_id
OPTIONS (
  description = 'SILVER pressure_surveys: typed, de-duplicated on (survey_id); loaded by lakehouse/load/bronze_to_silver.py.',
  labels = [('app', 'wellpulse'), ('stage', 'x'), ('datacloud', 'jetski')]
);

CREATE TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_silver.tubing_string` (
  `well_id` STRING NOT NULL,
  `field` STRING,
  `cluster_id` STRING,
  `seq` INT64 NOT NULL,
  `component` STRING,
  `od_in` FLOAT64,
  `length_m` FLOAT64,
  `top_m` FLOAT64,
  `install_date` DATE,
  `workover_id` STRING,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64 OPTIONS(description='0-based row ordinal in the landing file (preserves file order)'),
  `_landing_folder` STRING OPTIONS(description='Landing folder: asset | geleki | lakwa | lakhmani'),
  `_bronze_dt` DATE OPTIONS(description='Bronze batch partition (dt=)'),
  `_silver_loaded_at` TIMESTAMP OPTIONS(description='Silver load time')
)
CLUSTER BY well_id
OPTIONS (
  description = 'SILVER tubing_string: typed, de-duplicated on (well_id, seq); loaded by lakehouse/load/bronze_to_silver.py.',
  labels = [('app', 'wellpulse'), ('stage', 'x'), ('datacloud', 'jetski')]
);

CREATE TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_silver.well_master` (
  `well_id` STRING NOT NULL,
  `field` STRING,
  `asset` STRING,
  `latitude` FLOAT64,
  `longitude` FLOAT64,
  `spud_date` DATE,
  `completion_date` DATE,
  `current_zone` STRING,
  `perf_top_m` FLOAT64,
  `perf_bottom_m` FLOAT64,
  `total_depth_md_m` FLOAT64,
  `total_depth_tvd_m` FLOAT64,
  `max_dls_deg_30m` FLOAT64,
  `lift_type` STRING,
  `plunger_diameter_in` FLOAT64,
  `stroke_length_in` FLOAT64,
  `pump_setting_depth_m` FLOAT64,
  `rod_string_grade` STRING,
  `pump_type` STRING,
  `casing_vented` BOOL,
  `tubing_size_in` FLOAT64,
  `casing_size_in` FLOAT64,
  `status` STRING,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `cluster_id` STRING,
  `_source_row` INT64 OPTIONS(description='0-based row ordinal in the landing file (preserves file order)'),
  `_landing_folder` STRING OPTIONS(description='Landing folder: asset | geleki | lakwa | lakhmani'),
  `_bronze_dt` DATE OPTIONS(description='Bronze batch partition (dt=)'),
  `_silver_loaded_at` TIMESTAMP OPTIONS(description='Silver load time')
)
CLUSTER BY well_id
OPTIONS (
  description = 'SILVER well_master: typed, de-duplicated on (well_id); loaded by lakehouse/load/bronze_to_silver.py.',
  labels = [('app', 'wellpulse'), ('stage', 'x'), ('datacloud', 'jetski')]
);

CREATE TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_silver.well_offsets` (
  `well_id` STRING NOT NULL,
  `offset_well_id` STRING NOT NULL,
  `distance_m` FLOAT64,
  `same_zone` BOOL,
  `rank` INT64,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64 OPTIONS(description='0-based row ordinal in the landing file (preserves file order)'),
  `_landing_folder` STRING OPTIONS(description='Landing folder: asset | geleki | lakwa | lakhmani'),
  `_bronze_dt` DATE OPTIONS(description='Bronze batch partition (dt=)'),
  `_silver_loaded_at` TIMESTAMP OPTIONS(description='Silver load time')
)
CLUSTER BY well_id
OPTIONS (
  description = 'SILVER well_offsets: typed, de-duplicated on (well_id, offset_well_id); loaded by lakehouse/load/bronze_to_silver.py.',
  labels = [('app', 'wellpulse'), ('stage', 'x'), ('datacloud', 'jetski')]
);

CREATE TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_silver.well_run` (
  `run_date` DATE NOT NULL,
  `well_id` STRING NOT NULL,
  `trigger_a` STRING,
  `trigger_a_days` INT64,
  `trigger_a_residual_pct` FLOAT64,
  `trigger_b` BOOL,
  `trigger_b_days_since` FLOAT64,
  `trigger_b_p50_days` FLOAT64,
  `trigger_c` STRING,
  `trigger_d` BOOL,
  `mechanism` STRING,
  `mechanism_confidence` STRING,
  `chan_class` STRING,
  `chan_wor_slope` FLOAT64,
  `fillage_gap_blpd` FLOAT64,
  `offset_verdict` STRING,
  `rejected_mechanisms` STRING,
  `ettf_days` FLOAT64,
  `ettf_ci_low` FLOAT64,
  `ettf_ci_high` FLOAT64,
  `hazard` FLOAT64,
  `recommended_job_code` STRING,
  `requires_rig` BOOL,
  `est_duration_days` FLOAT64,
  `p_success` FLOAT64,
  `p_success_n` INT64,
  `deferred_bbl_avoided` FLOAT64,
  `net_value` FLOAT64,
  `priority` FLOAT64,
  `rank_overall` FLOAT64,
  `rank_within_queue` FLOAT64,
  `queue` STRING,
  `logistics_blocker` STRING,
  `earliest_start_date` DATE,
  `tool_trace` STRING,
  `model_version` STRING,
  `config_version` STRING,
  `data_as_of` DATE,
  `data_lag_days` INT64,
  `run_confidence` STRING,
  `confidence_reason` STRING,
  `tested_days_90d` INT64,
  `allocation_basis_id` STRING,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64 OPTIONS(description='0-based row ordinal in the landing file (preserves file order)'),
  `_landing_folder` STRING OPTIONS(description='Landing folder: asset | geleki | lakwa | lakhmani'),
  `_bronze_dt` DATE OPTIONS(description='Bronze batch partition (dt=)'),
  `_silver_loaded_at` TIMESTAMP OPTIONS(description='Silver load time')
)
CLUSTER BY well_id
OPTIONS (
  description = 'SILVER well_run: typed, de-duplicated on (run_date, well_id); loaded by lakehouse/load/bronze_to_silver.py.',
  labels = [('app', 'wellpulse'), ('stage', 'x'), ('datacloud', 'jetski')]
);

CREATE TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_silver.well_status_history` (
  `episode_id` STRING NOT NULL,
  `well_id` STRING,
  `status` STRING,
  `start_date` DATE,
  `end_date` DATE,
  `reason_code` STRING,
  `is_rigless` BOOL,
  `workover_id` STRING,
  `deferred_bbl` FLOAT64,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `field` STRING,
  `cluster_id` STRING,
  `is_prepend` BOOL,
  `_source_row` INT64 OPTIONS(description='0-based row ordinal in the landing file (preserves file order)'),
  `_landing_folder` STRING OPTIONS(description='Landing folder: asset | geleki | lakwa | lakhmani'),
  `_bronze_dt` DATE OPTIONS(description='Bronze batch partition (dt=)'),
  `_silver_loaded_at` TIMESTAMP OPTIONS(description='Silver load time')
)
CLUSTER BY well_id
OPTIONS (
  description = 'SILVER well_status_history: typed, de-duplicated on (episode_id); loaded by lakehouse/load/bronze_to_silver.py.',
  labels = [('app', 'wellpulse'), ('stage', 'x'), ('datacloud', 'jetski')]
);

CREATE TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_silver.well_tests` (
  `test_id` STRING NOT NULL,
  `well_id` STRING,
  `test_date` DATE,
  `test_duration_hr` FLOAT64,
  `oil_rate_bopd` FLOAT64,
  `water_rate_bwpd` FLOAT64,
  `gas_rate_mscfd` FLOAT64,
  `thp_kgcm2` FLOAT64,
  `chp_kgcm2` FLOAT64,
  `fluid_level_m` FLOAT64,
  `pump_intake_p_kgcm2` FLOAT64,
  `test_quality` STRING,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `field` STRING,
  `cluster_id` STRING,
  `is_prepend` BOOL,
  `_source_row` INT64 OPTIONS(description='0-based row ordinal in the landing file (preserves file order)'),
  `_landing_folder` STRING OPTIONS(description='Landing folder: asset | geleki | lakwa | lakhmani'),
  `_bronze_dt` DATE OPTIONS(description='Bronze batch partition (dt=)'),
  `_silver_loaded_at` TIMESTAMP OPTIONS(description='Silver load time')
)
CLUSTER BY well_id
OPTIONS (
  description = 'SILVER well_tests: typed, de-duplicated on (test_id); loaded by lakehouse/load/bronze_to_silver.py.',
  labels = [('app', 'wellpulse'), ('stage', 'x'), ('datacloud', 'jetski')]
);

CREATE TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_silver.workover_history` (
  `workover_id` STRING NOT NULL,
  `well_id` STRING,
  `start_date` DATE,
  `end_date` DATE,
  `job_code` STRING,
  `failure_code` STRING,
  `is_rigless` BOOL,
  `rig_id` STRING,
  `rig_days` FLOAT64,
  `pre_job_oil_bopd` FLOAT64,
  `post_job_oil_bopd` FLOAT64,
  `uplift_bopd` FLOAT64,
  `outcome` STRING,
  `run_life_days` INT64,
  `is_censored` BOOL,
  `damage_reset_frac` FLOAT64,
  `report_doc_id` STRING,
  `catalogue_job_code` STRING,
  `intervention_class` STRING,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `field` STRING,
  `cluster_id` STRING,
  `is_prepend` BOOL,
  `_source_row` INT64 OPTIONS(description='0-based row ordinal in the landing file (preserves file order)'),
  `_landing_folder` STRING OPTIONS(description='Landing folder: asset | geleki | lakwa | lakhmani'),
  `_bronze_dt` DATE OPTIONS(description='Bronze batch partition (dt=)'),
  `_silver_loaded_at` TIMESTAMP OPTIONS(description='Silver load time')
)
CLUSTER BY well_id
OPTIONS (
  description = 'SILVER workover_history: typed, de-duplicated on (workover_id); loaded by lakehouse/load/bronze_to_silver.py.',
  labels = [('app', 'wellpulse'), ('stage', 'x'), ('datacloud', 'jetski')]
);

CREATE TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_silver.cluster_master` (
  `cluster_id` STRING NOT NULL,
  `field` STRING,
  `cluster_type` STRING,
  `polygon_ref` STRING,
  `center_lat` FLOAT64,
  `center_lon` FLOAT64,
  `n_wells` INT64,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64 OPTIONS(description='0-based row ordinal in the landing file (preserves file order)'),
  `_landing_folder` STRING OPTIONS(description='Landing folder: asset | geleki | lakwa | lakhmani'),
  `_bronze_dt` DATE OPTIONS(description='Bronze batch partition (dt=)'),
  `_silver_loaded_at` TIMESTAMP OPTIONS(description='Silver load time')
)
CLUSTER BY field, cluster_id
OPTIONS (
  description = 'SILVER cluster_master: typed, de-duplicated on (cluster_id); loaded by lakehouse/load/bronze_to_silver.py.',
  labels = [('app', 'wellpulse'), ('stage', 'x'), ('datacloud', 'jetski')]
);

CREATE TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_silver.facility_master` (
  `facility_id` STRING NOT NULL,
  `field` STRING,
  `type` STRING,
  `name` STRING,
  `lat` FLOAT64,
  `lon` FLOAT64,
  `capacity_bopd` INT64,
  `serviced_cluster_ids` STRING,
  `compressor_capacity_mmscfd` FLOAT64,
  `water_handling_bwpd` FLOAT64,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64 OPTIONS(description='0-based row ordinal in the landing file (preserves file order)'),
  `_landing_folder` STRING OPTIONS(description='Landing folder: asset | geleki | lakwa | lakhmani'),
  `_bronze_dt` DATE OPTIONS(description='Bronze batch partition (dt=)'),
  `_silver_loaded_at` TIMESTAMP OPTIONS(description='Silver load time')
)
CLUSTER BY field, facility_id
OPTIONS (
  description = 'SILVER facility_master: typed, de-duplicated on (facility_id); loaded by lakehouse/load/bronze_to_silver.py.',
  labels = [('app', 'wellpulse'), ('stage', 'x'), ('datacloud', 'jetski')]
);

CREATE TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_silver.field_master` (
  `field` STRING NOT NULL,
  `asset` STRING,
  `prefix` STRING,
  `centroid_lat` FLOAT64,
  `centroid_lon` FLOAT64,
  `n_wells` INT64,
  `primary_reservoirs` STRING,
  `boundary_geojson` STRING,
  `is_synthetic_geometry` BOOL,
  `data_start` DATE,
  `data_end` DATE,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64 OPTIONS(description='0-based row ordinal in the landing file (preserves file order)'),
  `_landing_folder` STRING OPTIONS(description='Landing folder: asset | geleki | lakwa | lakhmani'),
  `_bronze_dt` DATE OPTIONS(description='Bronze batch partition (dt=)'),
  `_silver_loaded_at` TIMESTAMP OPTIONS(description='Silver load time')
)
CLUSTER BY field
OPTIONS (
  description = 'SILVER field_master: typed, de-duplicated on (field); loaded by lakehouse/load/bronze_to_silver.py.',
  labels = [('app', 'wellpulse'), ('stage', 'x'), ('datacloud', 'jetski')]
);

CREATE TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_silver.field_targets` (
  `field` STRING NOT NULL,
  `month` DATE NOT NULL,
  `target_oil_bopd` FLOAT64,
  `target_uptime_pct` FLOAT64,
  `potential_oil_bopd` FLOAT64,
  `plan_efficiency` FLOAT64,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64 OPTIONS(description='0-based row ordinal in the landing file (preserves file order)'),
  `_landing_folder` STRING OPTIONS(description='Landing folder: asset | geleki | lakwa | lakhmani'),
  `_bronze_dt` DATE OPTIONS(description='Bronze batch partition (dt=)'),
  `_silver_loaded_at` TIMESTAMP OPTIONS(description='Silver load time')
)
CLUSTER BY field, month
OPTIONS (
  description = 'SILVER field_targets: typed, de-duplicated on (field, month); loaded by lakehouse/load/bronze_to_silver.py.',
  labels = [('app', 'wellpulse'), ('stage', 'x'), ('datacloud', 'jetski')]
);

CREATE TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_silver.job_catalogue` (
  `job_code` STRING NOT NULL,
  `job_name` STRING,
  `category` STRING,
  `mechanism_code` STRING,
  `selection_evidence` STRING,
  `requires_rig` BOOL,
  `equipment` STRING,
  `est_days` FLOAT64,
  `est_cost_lakh_inr` FLOAT64,
  `cost_band` STRING,
  `intervention_class` STRING,
  `sop_doc_id` STRING,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64 OPTIONS(description='0-based row ordinal in the landing file (preserves file order)'),
  `_landing_folder` STRING OPTIONS(description='Landing folder: asset | geleki | lakwa | lakhmani'),
  `_bronze_dt` DATE OPTIONS(description='Bronze batch partition (dt=)'),
  `_silver_loaded_at` TIMESTAMP OPTIONS(description='Silver load time')
)
CLUSTER BY job_code
OPTIONS (
  description = 'SILVER job_catalogue: typed, de-duplicated on (job_code); loaded by lakehouse/load/bronze_to_silver.py.',
  labels = [('app', 'wellpulse'), ('stage', 'x'), ('datacloud', 'jetski')]
);

CREATE TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_silver.mro_inventory` (
  `item_code` STRING NOT NULL,
  `item_name` STRING,
  `base` STRING NOT NULL,
  `qty_on_hand` INT64,
  `transit_days` INT64,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64 OPTIONS(description='0-based row ordinal in the landing file (preserves file order)'),
  `_landing_folder` STRING OPTIONS(description='Landing folder: asset | geleki | lakwa | lakhmani'),
  `_bronze_dt` DATE OPTIONS(description='Bronze batch partition (dt=)'),
  `_silver_loaded_at` TIMESTAMP OPTIONS(description='Silver load time')
)
CLUSTER BY item_code
OPTIONS (
  description = 'SILVER mro_inventory: typed, de-duplicated on (item_code, base); loaded by lakehouse/load/bronze_to_silver.py.',
  labels = [('app', 'wellpulse'), ('stage', 'x'), ('datacloud', 'jetski')]
);

CREATE TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_silver.rig_calendar` (
  `rig_id` STRING NOT NULL,
  `date` DATE NOT NULL,
  `status` STRING,
  `well_id` STRING,
  `rig_class` STRING,
  `_ingested_at` STRING,
  `_source_system` STRING,
  `_source_file` STRING,
  `_batch_id` STRING,
  `_source_row` INT64 OPTIONS(description='0-based row ordinal in the landing file (preserves file order)'),
  `_landing_folder` STRING OPTIONS(description='Landing folder: asset | geleki | lakwa | lakhmani'),
  `_bronze_dt` DATE OPTIONS(description='Bronze batch partition (dt=)'),
  `_silver_loaded_at` TIMESTAMP OPTIONS(description='Silver load time')
)
CLUSTER BY rig_id
OPTIONS (
  description = 'SILVER rig_calendar: typed, de-duplicated on (rig_id, date); loaded by lakehouse/load/bronze_to_silver.py.',
  labels = [('app', 'wellpulse'), ('stage', 'x'), ('datacloud', 'jetski')]
);
