-- GENERATED by lakehouse/ddl/generate_ddl.py from the landing parquet schemas. Do not edit by hand.

CREATE TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_silver.doc_chunks` (
  `chunk_id` STRING NOT NULL OPTIONS(description='doc_id + page + chunk ordinal'),
  `doc_id` STRING NOT NULL OPTIONS(description='document_index.doc_id'),
  `page` INT64 OPTIONS(description='1-based PDF page'),
  `chunk_seq` INT64 OPTIONS(description='0-based chunk ordinal within the page'),
  `text` STRING OPTIONS(description='Extracted text of the chunk (same text the TF-IDF index was built from)'),
  `well_id` STRING OPTIONS(description='Well the document belongs to (NULL for field-level docs and SOPs)'),
  `field` STRING OPTIONS(description='Geleki | Lakwa | Lakhmani (NULL for asset-wide SOPs)'),
  `doc_type` STRING OPTIONS(description='D1..D11 or SOP'),
  `doc_date` DATE,
  `gcs_uri` STRING OPTIONS(description='gs://.../documents/... PDF object'),
  `char_count` INT64,
  `index_version` STRING OPTIONS(description='TF-IDF index build id / sha the chunk was mirrored from'),
  `_silver_loaded_at` TIMESTAMP
)
CLUSTER BY field, doc_type, doc_id
OPTIONS (
  description = 'SILVER doc_chunks: mirror of the TF-IDF retrieval index over D1-D11 PDFs and SOPs (D-17; Vertex AI Search drop-in later). Loaded by lakehouse/load/doc_chunks.py.',
  labels = [('app', 'wellpulse'), ('stage', 'x'), ('datacloud', 'jetski')]
);
