-- GENERATED by lakehouse/ddl/generate_ddl.py from the landing parquet schemas. Do not edit by hand.

CREATE TABLE IF NOT EXISTS `workover-operations-agentic-ai.wellpulse_gold.dossier_facts` (
  `doc_id` STRING NOT NULL OPTIONS(description='Document whose facts.json this row came from'),
  `well_id` STRING,
  `field` STRING,
  `doc_type` STRING,
  `fact_key` STRING NOT NULL OPTIONS(description='Flattened JSON path inside facts.json'),
  `fact_value` STRING OPTIONS(description='Value as text (numbers keep their source formatting)'),
  `fact_number` FLOAT64 OPTIONS(description='Numeric value when fact_value parses as a number'),
  `facts_sha256` STRING OPTIONS(description='document_index.facts_sha256 of the source facts.json'),
  `_loaded_at` TIMESTAMP
)
CLUSTER BY field, well_id, doc_id
OPTIONS (
  description = 'GOLD dossier_facts: grounding facts behind every generated document/dossier (V5 grounding cache, derived interpretation SDD 15.1). Loaded by lakehouse/load/dossier_facts.py.',
  labels = [('app', 'wellpulse'), ('stage', 'x'), ('datacloud', 'jetski')]
);
