"""Generate the medallion DDL from the landing parquet schemas (X-F1, SDD §15.1).

The Stage N parquet files are the data contract, so the DDL is derived from them rather than
typed by hand: one source of truth, no drift. Run from the repo root or anywhere:

    uv run --project backend python lakehouse/ddl/generate_ddl.py

Writes (all idempotent: ``CREATE ... IF NOT EXISTS``; nothing is ever dropped):
    00_datasets.sql          wellpulse_bronze / wellpulse_silver / wellpulse_gold (asia-south1)
    10_bronze_external.sql   one external table per landing table over gs://.../bronze/<table>/
    20_silver_tables.sql     typed Silver contract tables (partitioned + clustered)
    30_silver_doc_chunks.sql doc_chunks mirror of the TF-IDF index (D-17)
    40_gold_loader_tables.sql dossier_facts (loaded by lakehouse/load/dossier_facts.py)
"""

from __future__ import annotations

import sys
from pathlib import Path

import pyarrow.parquet as pq

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from lakehouse import config as C

OUT = Path(__file__).resolve().parent
HEADER = "-- GENERATED by lakehouse/ddl/generate_ddl.py from the landing parquet schemas. Do not edit by hand.\n"


def _labels_sql() -> str:
    return "[" + ", ".join(f"('{k}', '{v}')" for k, v in C.LABELS.items()) + "]"


def contract_schema(paths: list[Path]) -> list[tuple[str, str]]:
    """Column list in the first file's order (Geleki first = parquet-repository concat order)."""
    first = pq.read_schema(paths[0])
    cols = [(f.name, C.ARROW_TO_BQ[str(f.type)]) for f in first]
    names = {c for c, _ in cols}
    for p in paths[1:]:
        for f in pq.read_schema(p):
            if f.name not in names:  # union, appended (none today; kept for safety)
                cols.append((f.name, C.ARROW_TO_BQ[str(f.type)]))
                names.add(f.name)
    return cols


def datasets_sql() -> str:
    parts = [HEADER]
    desc = {
        C.BRONZE_DATASET: "WellPulse BRONZE: immutable landing parquet in GCS exposed as external tables (SDD 15.1).",
        C.SILVER_DATASET: "WellPulse SILVER: typed, de-duplicated contract tables; daily_production partitioned by date, clustered by field, well_id.",
        C.GOLD_DATASET: "WellPulse GOLD: Dataform-built KPIs, screening views, feature store, NBA lookup, dossier facts.",
    }
    for ds, d in desc.items():
        parts.append(
            f"CREATE SCHEMA IF NOT EXISTS `{C.PROJECT_ID}.{ds}`\n"
            f"OPTIONS (location = '{C.LOCATION}', description = '{d}', labels = {_labels_sql()});\n"
        )
    return "\n".join(parts)


def bronze_sql(tables: dict[str, list[Path]]) -> str:
    parts = [HEADER]
    for t, paths in tables.items():
        cols = contract_schema(paths) + [("_source_row", "INT64")]
        col_sql = ",\n  ".join(f"`{c}` {typ}" for c, typ in cols)
        prefix = C.gcs(C.BRONZE_PREFIX, t)
        parts.append(
            f"CREATE EXTERNAL TABLE IF NOT EXISTS {C.fq(C.BRONZE_DATASET, t)} (\n  {col_sql}\n)\n"
            f"WITH PARTITION COLUMNS (dt DATE, landing_folder STRING)\n"
            f"OPTIONS (\n  format = 'PARQUET',\n  uris = ['{prefix}/*'],\n"
            f"  hive_partition_uri_prefix = '{prefix}',\n  require_hive_partition_filter = false,\n"
            # NB: external-table DDL rejects OPTIONS(labels=...); labels are set by apply_ddl.py afterwards.
            f"  description = 'BRONZE {t}: landing parquet as delivered (+ _source_row ordinal); hive keys dt, landing_folder.'\n);\n"
        )
    return "\n".join(parts)


def silver_sql(tables: dict[str, list[Path]]) -> str:
    parts = [HEADER]
    for t, paths in tables.items():
        cols = contract_schema(paths) + [
            ("_source_row", "INT64 OPTIONS(description='0-based row ordinal in the landing file (preserves file order)')"),
            ("_landing_folder", "STRING OPTIONS(description='Landing folder: asset | geleki | lakwa | lakhmani')"),
            ("_bronze_dt", "DATE OPTIONS(description='Bronze batch partition (dt=)')"),
            ("_silver_loaded_at", "TIMESTAMP OPTIONS(description='Silver load time')"),
        ]
        names = [c for c, _ in cols]
        nn = set(C.TABLE_KEYS[t])
        col_sql = ",\n  ".join(f"`{c}` {typ}{' NOT NULL' if c in nn else ''}" if "OPTIONS" not in typ
                               else f"`{c}` {typ}" for c, typ in cols)
        part = f"PARTITION BY {C.SILVER_PARTITION[t]}\n" if t in C.SILVER_PARTITION else ""
        cluster = [c for c in C.SILVER_CLUSTER.get(t, C.DEFAULT_CLUSTER) if c in names][:4]
        clu = f"CLUSTER BY {', '.join(cluster)}\n" if cluster else ""
        key = ", ".join(C.TABLE_KEYS[t])
        parts.append(
            f"CREATE TABLE IF NOT EXISTS {C.fq(C.SILVER_DATASET, t)} (\n  {col_sql}\n)\n{part}{clu}"
            f"OPTIONS (\n  description = 'SILVER {t}: typed, de-duplicated on ({key}); loaded by lakehouse/load/bronze_to_silver.py.',\n"
            f"  labels = {_labels_sql()}\n);\n"
        )
    return "\n".join(parts)


def doc_chunks_sql() -> str:
    return HEADER + f"""
CREATE TABLE IF NOT EXISTS {C.fq(C.SILVER_DATASET, 'doc_chunks')} (
  `chunk_id` STRING NOT NULL OPTIONS(description='doc_id + page + chunk ordinal'),
  `doc_id` STRING NOT NULL OPTIONS(description='document_index.doc_id'),
  `page` INT64 OPTIONS(description='1-based PDF page'),
  `chunk_seq` INT64 OPTIONS(description='0-based chunk ordinal within the page'),
  `text` STRING OPTIONS(description='Extracted text of the chunk (same text the TF-IDF index was built from)'),
  `well_id` STRING OPTIONS(description='Well the document belongs to (NULL for field-level docs and SOPs)'),
  `field` STRING OPTIONS(description='Geleki | Lakwa | Lakhmani (NULL for asset-wide SOPs)'),
  `doc_type` STRING OPTIONS(description='D1..D11 or SOP'),
  `doc_date` DATE,
  `gcs_uri` STRING OPTIONS(description='gs://.../documents/... PDF object'),
  `char_count` INT64,
  `index_version` STRING OPTIONS(description='TF-IDF index build id / sha the chunk was mirrored from'),
  `_silver_loaded_at` TIMESTAMP
)
CLUSTER BY field, doc_type, doc_id
OPTIONS (
  description = 'SILVER doc_chunks: mirror of the TF-IDF retrieval index over D1-D11 PDFs and SOPs (D-17; Vertex AI Search drop-in later). Loaded by lakehouse/load/doc_chunks.py.',
  labels = {_labels_sql()}
);
"""


def gold_loader_sql() -> str:
    return HEADER + f"""
CREATE TABLE IF NOT EXISTS {C.fq(C.GOLD_DATASET, 'dossier_facts')} (
  `doc_id` STRING NOT NULL OPTIONS(description='Document whose facts.json this row came from'),
  `well_id` STRING,
  `field` STRING,
  `doc_type` STRING,
  `fact_key` STRING NOT NULL OPTIONS(description='Flattened JSON path inside facts.json'),
  `fact_value` STRING OPTIONS(description='Value as text (numbers keep their source formatting)'),
  `fact_number` FLOAT64 OPTIONS(description='Numeric value when fact_value parses as a number'),
  `facts_sha256` STRING OPTIONS(description='document_index.facts_sha256 of the source facts.json'),
  `_loaded_at` TIMESTAMP
)
CLUSTER BY field, well_id, doc_id
OPTIONS (
  description = 'GOLD dossier_facts: grounding facts behind every generated document/dossier (V5 grounding cache, derived interpretation SDD 15.1). Loaded by lakehouse/load/dossier_facts.py.',
  labels = {_labels_sql()}
);
"""


def main() -> int:
    tables = C.landing_tables()
    missing = set(tables) ^ set(C.TABLE_KEYS)
    if missing:
        raise SystemExit(f"TABLE_KEYS out of sync with landing tables: {sorted(missing)}")
    files = {
        "00_datasets.sql": datasets_sql(),
        "10_bronze_external.sql": bronze_sql(tables),
        "20_silver_tables.sql": silver_sql(tables),
        "30_silver_doc_chunks.sql": doc_chunks_sql(),
        "40_gold_loader_tables.sql": gold_loader_sql(),
    }
    for name, sql in files.items():
        (OUT / name).write_text(sql)
        print(f"wrote {name} ({sql.count('CREATE')} statements)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
